import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import '@/styles/globals.css';
import { inter } from '@/styles/fonts/inter';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
